### ISSUE TITLE
install fails on Win 10, due to missing 'cairo.h' trying to build Canvas

### ISSUE THREAD

**Issue by wayne-optin** [rickvandermey/angular-starterkit#2]
Clone from github, run ```npm i``` and get many errors installing after it turns out the version of Canvas isn't available pre-built.

(There isn't a v72 for win32, though there is a v67, at https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.5.0/canvas-v2.5.0-node-v67-win32-unknown-x64.tar.gz)

The output is:
```
> canvas@2.5.0 install C:\Users\wayne\dev\angulartests\angular-starterkit\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.5.0/canvas-v2.5.0-node-v72-win32-unknown-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.5.0 and node@12.4.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
Warning: Missing input files:
C:\GTK\bin\libpangoft2-1.0-0.dll
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libintl-8.dll
C:\GTK\bin\libgmodule-2.0-0.dll
C:\GTK\bin\libglib-2.0-0.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libgobject-2.0-0.dll
C:\GTK\bin\libgthread-2.0-0.dll
C:\GTK\bin\libpangocairo-1.0-0.dll
C:\GTK\bin\libfreetype-6.dll
C:\GTK\bin\libpango-1.0-0.dll
C:\GTK\bin\libpangowin32-1.0-0.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Backend.cc
  ImageBackend.cc
  PdfBackend.cc
  SvgBackend.cc
  BMPParser.cc
  Backends.cc
  Canvas.cc
  CanvasGradient.cc
c:\users\wayne\dev\angulartests\angular-starterkit\node_modules\canvas\src\backend\backend.h(3): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\backend\PdfBackend.cc)  [C:\Users\wayne\dev\angulartests\angular-starterkit\node_modules\canvas\build\canvas.vcxproj]
```

The missing 'cairo.h' problem then happens over and over until finally:

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\wayne\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wayne\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\wayne\\dev\\angulartests\\angular-starterkit\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\wayne\\dev\\angulartests\\angular-starterkit\\node_modules\\canvas\\build\\Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd C:\Users\wayne\dev\angulartests\angular-starterkit\node_modules\canvas
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\wayne\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\wayne\dev\angulartests\angular-starterkit\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\wayne\dev\angulartests\angular-starterkit\node_modules\canvas\build\Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\wayne\dev\angulartests\angular-starterkit\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wayne\\dev\\angulartests\\angular-starterkit\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\wayne\dev\angulartests\angular-starterkit\node_modules\canvas
node-pre-gyp ERR! node -v v12.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\wayne\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\wayne\dev\angulartests\angular-starterkit\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\wayne\dev\angulartests\angular-starterkit\node_modules\canvas\build\Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
```

**Comment by rickvandermey** [comment]
I do not have a windows PC, so I need to figure out how to reproduce. It looks like a dependency of a dependency. Need to figure out which. 

From a quick search, it seems python v3.x.x is not supported for node-canvas. If you try with version 2.7.x will it work?

Have you tried install it as the wiki suggest: https://github.com/Automattic/node-canvas/wiki/Installation:-Windows

Sent from mobile

**Comment by wayne-optin** [comment]
BTW, I think the dep on canvas is ocming from:
```
λ npm ls canvas
RVDM-Angular-Starterkit@1.1.2 C:\Users\wayne\dev\angulartests\angular-starterkit
`-- protractor-image-comparison@3.3.0
  `-- webdriver-image-comparison@0.6.0
    `-- canvas@2.5.0
```
and backleveling to protractor-image-comparison@3.2.0 installs but the tests don't pass; ```run test``` and ```run test:unit-headless``` both fail on not finding an ```en.json``` file, like this:
```
 10% building 3/3 modules 0 active10 07 2019 14:16:34.166:WARN [karma]: No captured browser, open http://localhost:9876/
10 07 2019 14:16:34.173:INFO [karma-server]: Karma v4.1.0 server started at http://0.0.0.0:9876/
10 07 2019 14:16:34.174:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
10 07 2019 14:16:34.178:INFO [launcher]: Starting browser Chrome

ERROR in ./src/app/app.component.spec.ts
Module not found: Error: Can't resolve '../assets/i18n/en.json' in 'C:\Users\wayne\dev\angulartests\angular-starterkit\src\app'
resolve '../assets/i18n/en.json' in 'C:\Users\wayne\dev\angulartests\angular-starterkit\src\app'
  using description file: C:\Users\wayne\dev\angulartests\angular-starterkit\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\Users\wayne\dev\angulartests\angular-starterkit\package.json (relative path: ./src/assets/i18n/en.json)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\wayne\dev\angulartests\angular-starterkit\src\assets\i18n\en.json doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\wayne\dev\angulartests\angular-starterkit\src\assets\i18n\en.json.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\wayne\dev\angulartests\angular-starterkit\src\assets\i18n\en.json.tsx doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\wayne\dev\angulartests\angular-starterkit\src\assets\i18n\en.json.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\wayne\dev\angulartests\angular-starterkit\src\assets\i18n\en.json.js doesn't exist
      as directory
        C:\Users\wayne\dev\angulartests\angular-starterkit\src\assets\i18n\en.json doesn't exist
[C:\Users\wayne\dev\angulartests\angular-starterkit\src\assets\i18n\en.json]
[C:\Users\wayne\dev\angulartests\angular-starterkit\src\assets\i18n\en.json.ts]
[C:\Users\wayne\dev\angulartests\angular-starterkit\src\assets\i18n\en.json.tsx]
[C:\Users\wayne\dev\angulartests\angular-starterkit\src\assets\i18n\en.json.mjs]
[C:\Users\wayne\dev\angulartests\angular-starterkit\src\assets\i18n\en.json.js]
 @ ./src/app/app.component.spec.ts 18:19-52
 @ ./src/app sync \.ts
 @ ./src/test.ts
```

**Comment by wayne-optin** [comment]
My PC runs python 2.7.16, at least that's what I get if I just enter ```python``` at the command line.

**Comment by rickvandermey** [comment]
will remove image comparison for now, because it was a work in progress.
